### ISSUE TITLE
Execution problem 

### ISSUE THREAD

**Issue by niranjan8129** [qjadud1994/CRNN-Keras#13]
Hi, You are did a great job and model. I liked very much. I have 2 issues . see the blow and help me out 
 
1) while run trainin.py job i get below error

Traceback (most recent call last):
  File "training.py", line 41, in <module>
    validation_steps=int(tiger_val.n / val_batch_size))
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 68, in fit_generator
    raise ValueError('`validation_steps=None` is only valid for a'
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.

#2  ) if I change  validation_steps=int(tiger_val.n / val_batch_size)) to validation_steps=20 , I get below error. Kindly suggest me why I am getting these errors.

Epoch 1/30
Traceback (most recent call last):
  File "training.py", line 41, in <module>
    validation_steps=5)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\callbacks.py", line 338, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

**Comment by K0BigYang** [comment]
You can try like this :

model.fit_generator(generator=tiger_train.next_batch(),
                    steps_per_epoch=ceil(tiger_train.n / batch_size),
                    epochs=30,
                    callbacks=[checkpoint],
                    validation_data=tiger_val.next_batch(),
                    validation_steps=ceil(tiger_val.n / val_batch_size))

**Comment by QsmQls** [comment]
validation_steps = int(val_batch_size/tiger_val.n)

**Comment by mouad12345** [comment]
your batch size greater than your dataset train
change your batch_size or add more dataset images
