### ISSUE TITLE
How to generate images?

### ISSUE THREAD

**Issue by Yili-Zhang** [qjadud1994/CRNN-Keras#33]
Hi,

I am new to neural network, so my question might be dumb.

After setting  the correct environment and imported the correct library, I started to run the training.py file, but I constantly get a error:
`ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.`

And here is the whole output in the  console:
`Using TensorFlow backend.
2019-04-22 19:07:01.124992: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
...New weight data...
4  Image Loading start...
True
4  Image Loading finish...
5  Image Loading start...
True
5  Image Loading finish...
Traceback (most recent call last):
  File "C:/Users/A02295947/Documents/Pycharm Projects/CRNN-Keras-master/training.py", line 41, in <module>
    validation_steps=int(tiger_val.n / val_batch_size))
  File "C:\Users\A02295947\AppData\Local\Continuum\anaconda2\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\A02295947\AppData\Local\Continuum\anaconda2\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 2053, in fit_generator
    raise ValueError('`validation_steps=None` is only valid for a'
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.

Process finished with exit code 1`

With mu friends' help, the conclusion was the training pictures are not enough. But I looked at your code, the "training.py" would ran the "Image_Generator.py" inside, so I guess the program would automatically generate images for the users? Otherwise what should I do to generate enough amount of images as I need?

Thanks,

-Yili

**Comment by pendex900x** [comment]
I have got same error, could you solve it?
